-- ============================================================================
-- 오라클 데이터베이스 테이블 정의 (Oracle Database Table Definitions)
-- 정보보안 시스템용 (For Information Security System)
-- ============================================================================

-- ============================================================================
-- 1. 사용자 관리 테이블 (User Management Tables)
-- ============================================================================

-- 사용자 정보 테이블
CREATE TABLE USERS (
    USER_ID         NUMBER(10)      PRIMARY KEY,
    USERNAME        VARCHAR2(50)    NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(256)   NOT NULL,
    EMAIL           VARCHAR2(100)   NOT NULL UNIQUE,
    FULL_NAME       VARCHAR2(100)   NOT NULL,
    PHONE_NUMBER    VARCHAR2(20),
    DEPARTMENT      VARCHAR2(50),
    POSITION        VARCHAR2(50),
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    ACCOUNT_LOCKED  CHAR(1)         DEFAULT 'N' CHECK (ACCOUNT_LOCKED IN ('Y', 'N')),
    FAILED_LOGIN_ATTEMPTS NUMBER(3)  DEFAULT 0,
    LAST_LOGIN      TIMESTAMP,
    PASSWORD_CHANGED_DATE TIMESTAMP,
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    MODIFIED_DATE   TIMESTAMP,
    MODIFIED_BY     VARCHAR2(50)
);

-- 사용자 ID 시퀀스
CREATE SEQUENCE SEQ_USER_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 역할 정보 테이블
CREATE TABLE ROLES (
    ROLE_ID         NUMBER(10)      PRIMARY KEY,
    ROLE_NAME       VARCHAR2(50)    NOT NULL UNIQUE,
    ROLE_DESC       VARCHAR2(200),
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    MODIFIED_DATE   TIMESTAMP,
    MODIFIED_BY     VARCHAR2(50)
);

-- 역할 ID 시퀀스
CREATE SEQUENCE SEQ_ROLE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 사용자-역할 매핑 테이블
CREATE TABLE USER_ROLES (
    USER_ROLE_ID    NUMBER(10)      PRIMARY KEY,
    USER_ID         NUMBER(10)      NOT NULL,
    ROLE_ID         NUMBER(10)      NOT NULL,
    ASSIGNED_DATE   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ASSIGNED_BY     VARCHAR2(50)    NOT NULL,
    EXPIRY_DATE     TIMESTAMP,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT UK_USER_ROLES UNIQUE (USER_ID, ROLE_ID)
);

-- 사용자-역할 ID 시퀀스
CREATE SEQUENCE SEQ_USER_ROLE_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================================
-- 2. 접근 제어 테이블 (Access Control Tables)
-- ============================================================================

-- 권한 정보 테이블
CREATE TABLE PERMISSIONS (
    PERMISSION_ID   NUMBER(10)      PRIMARY KEY,
    PERMISSION_NAME VARCHAR2(100)   NOT NULL UNIQUE,
    PERMISSION_DESC VARCHAR2(200),
    RESOURCE_TYPE   VARCHAR2(50)    NOT NULL,
    ACTION_TYPE     VARCHAR2(50)    NOT NULL CHECK (ACTION_TYPE IN ('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXECUTE')),
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL
);

-- 권한 ID 시퀀스
CREATE SEQUENCE SEQ_PERMISSION_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 역할-권한 매핑 테이블
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_PERMISSION_ID NUMBER(10)   PRIMARY KEY,
    ROLE_ID         NUMBER(10)      NOT NULL,
    PERMISSION_ID   NUMBER(10)      NOT NULL,
    GRANTED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    GRANTED_BY      VARCHAR2(50)    NOT NULL,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT FK_ROLE_PERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT FK_ROLE_PERM_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(PERMISSION_ID),
    CONSTRAINT UK_ROLE_PERMISSIONS UNIQUE (ROLE_ID, PERMISSION_ID)
);

-- 역할-권한 ID 시퀀스
CREATE SEQUENCE SEQ_ROLE_PERMISSION_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================================
-- 3. 감사 로그 테이블 (Audit Log Tables)
-- ============================================================================

-- 감사 로그 테이블
CREATE TABLE AUDIT_LOGS (
    AUDIT_ID        NUMBER(20)      PRIMARY KEY,
    USER_ID         NUMBER(10),
    USERNAME        VARCHAR2(50)    NOT NULL,
    ACTION_TYPE     VARCHAR2(50)    NOT NULL,
    RESOURCE_TYPE   VARCHAR2(50),
    RESOURCE_ID     VARCHAR2(100),
    ACTION_DESC     VARCHAR2(500),
    IP_ADDRESS      VARCHAR2(45),
    USER_AGENT      VARCHAR2(500),
    STATUS          VARCHAR2(20)    CHECK (STATUS IN ('SUCCESS', 'FAILURE', 'ERROR')),
    ERROR_MESSAGE   VARCHAR2(1000),
    SESSION_ID      VARCHAR2(100),
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 감사 로그 ID 시퀀스
CREATE SEQUENCE SEQ_AUDIT_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE;

-- 로그인 이력 테이블
CREATE TABLE LOGIN_HISTORY (
    LOGIN_ID        NUMBER(20)      PRIMARY KEY,
    USER_ID         NUMBER(10),
    USERNAME        VARCHAR2(50)    NOT NULL,
    LOGIN_TIME      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    LOGOUT_TIME     TIMESTAMP,
    IP_ADDRESS      VARCHAR2(45)    NOT NULL,
    USER_AGENT      VARCHAR2(500),
    LOGIN_STATUS    VARCHAR2(20)    CHECK (LOGIN_STATUS IN ('SUCCESS', 'FAILED', 'LOCKED')),
    FAILURE_REASON  VARCHAR2(200),
    SESSION_ID      VARCHAR2(100),
    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 로그인 이력 ID 시퀀스
CREATE SEQUENCE SEQ_LOGIN_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 100
    NOCYCLE;

-- ============================================================================
-- 4. 보안 정책 테이블 (Security Policy Tables)
-- ============================================================================

-- 보안 정책 테이블
CREATE TABLE SECURITY_POLICIES (
    POLICY_ID       NUMBER(10)      PRIMARY KEY,
    POLICY_NAME     VARCHAR2(100)   NOT NULL UNIQUE,
    POLICY_TYPE     VARCHAR2(50)    NOT NULL CHECK (POLICY_TYPE IN ('PASSWORD', 'ACCESS', 'NETWORK', 'DATA', 'AUDIT')),
    POLICY_DESC     VARCHAR2(500),
    POLICY_RULES    CLOB,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    SEVERITY_LEVEL  VARCHAR2(20)    CHECK (SEVERITY_LEVEL IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    EFFECTIVE_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRY_DATE     TIMESTAMP,
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    MODIFIED_DATE   TIMESTAMP,
    MODIFIED_BY     VARCHAR2(50)
);

-- 보안 정책 ID 시퀀스
CREATE SEQUENCE SEQ_POLICY_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 패스워드 정책 테이블
CREATE TABLE PASSWORD_POLICIES (
    PASSWORD_POLICY_ID NUMBER(10)   PRIMARY KEY,
    MIN_LENGTH      NUMBER(3)       DEFAULT 8 NOT NULL,
    MAX_LENGTH      NUMBER(3)       DEFAULT 128 NOT NULL,
    REQUIRE_UPPERCASE CHAR(1)       DEFAULT 'Y' CHECK (REQUIRE_UPPERCASE IN ('Y', 'N')),
    REQUIRE_LOWERCASE CHAR(1)       DEFAULT 'Y' CHECK (REQUIRE_LOWERCASE IN ('Y', 'N')),
    REQUIRE_DIGIT   CHAR(1)         DEFAULT 'Y' CHECK (REQUIRE_DIGIT IN ('Y', 'N')),
    REQUIRE_SPECIAL CHAR(1)         DEFAULT 'Y' CHECK (REQUIRE_SPECIAL IN ('Y', 'N')),
    MAX_AGE_DAYS    NUMBER(4)       DEFAULT 90,
    MIN_AGE_DAYS    NUMBER(4)       DEFAULT 1,
    PASSWORD_HISTORY_COUNT NUMBER(3) DEFAULT 5,
    MAX_LOGIN_ATTEMPTS NUMBER(3)    DEFAULT 5,
    LOCKOUT_DURATION_MINUTES NUMBER(5) DEFAULT 30,
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    MODIFIED_DATE   TIMESTAMP,
    MODIFIED_BY     VARCHAR2(50)
);

-- 패스워드 정책 ID 시퀀스
CREATE SEQUENCE SEQ_PASSWORD_POLICY_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 패스워드 이력 테이블
CREATE TABLE PASSWORD_HISTORY (
    HISTORY_ID      NUMBER(20)      PRIMARY KEY,
    USER_ID         NUMBER(10)      NOT NULL,
    PASSWORD_HASH   VARCHAR2(256)   NOT NULL,
    CHANGED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CHANGED_BY      VARCHAR2(50)    NOT NULL,
    CONSTRAINT FK_PWD_HISTORY_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 패스워드 이력 ID 시퀀스
CREATE SEQUENCE SEQ_PASSWORD_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    CACHE 50
    NOCYCLE;

-- ============================================================================
-- 5. 취약점 추적 테이블 (Vulnerability Tracking Tables)
-- ============================================================================

-- 취약점 정보 테이블
CREATE TABLE VULNERABILITIES (
    VULNERABILITY_ID NUMBER(10)     PRIMARY KEY,
    CVE_ID          VARCHAR2(50),
    VULNERABILITY_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION     CLOB,
    SEVERITY_LEVEL  VARCHAR2(20)    NOT NULL CHECK (SEVERITY_LEVEL IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CVSS_SCORE      NUMBER(3,1),
    AFFECTED_SYSTEM VARCHAR2(200),
    AFFECTED_VERSION VARCHAR2(100),
    STATUS          VARCHAR2(20)    DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'WONT_FIX')),
    DISCOVERY_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    RESOLUTION_DATE TIMESTAMP,
    ASSIGNED_TO     VARCHAR2(50),
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    MODIFIED_DATE   TIMESTAMP,
    MODIFIED_BY     VARCHAR2(50)
);

-- 취약점 ID 시퀀스
CREATE SEQUENCE SEQ_VULNERABILITY_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 보안 사고 테이블
CREATE TABLE SECURITY_INCIDENTS (
    INCIDENT_ID     NUMBER(10)      PRIMARY KEY,
    INCIDENT_TITLE  VARCHAR2(200)   NOT NULL,
    INCIDENT_TYPE   VARCHAR2(50)    NOT NULL CHECK (INCIDENT_TYPE IN ('BREACH', 'MALWARE', 'PHISHING', 'DOS', 'UNAUTHORIZED_ACCESS', 'DATA_LEAK', 'OTHER')),
    SEVERITY_LEVEL  VARCHAR2(20)    NOT NULL CHECK (SEVERITY_LEVEL IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    DESCRIPTION     CLOB,
    DETECTION_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    REPORTED_BY     VARCHAR2(50)    NOT NULL,
    ASSIGNED_TO     VARCHAR2(50),
    STATUS          VARCHAR2(20)    DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'CLOSED')),
    RESOLUTION_NOTES CLOB,
    RESOLUTION_DATE TIMESTAMP,
    IMPACT_ASSESSMENT VARCHAR2(500),
    AFFECTED_USERS  NUMBER(10),
    AFFECTED_SYSTEMS VARCHAR2(500),
    CREATED_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(50)    NOT NULL,
    MODIFIED_DATE   TIMESTAMP,
    MODIFIED_BY     VARCHAR2(50)
);

-- 보안 사고 ID 시퀀스
CREATE SEQUENCE SEQ_INCIDENT_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================================
-- 6. 인덱스 생성 (Create Indexes)
-- ============================================================================

-- 사용자 테이블 인덱스
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_IS_ACTIVE ON USERS(IS_ACTIVE);
CREATE INDEX IDX_USERS_DEPARTMENT ON USERS(DEPARTMENT);

-- 감사 로그 인덱스
CREATE INDEX IDX_AUDIT_USER_ID ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_USERNAME ON AUDIT_LOGS(USERNAME);
CREATE INDEX IDX_AUDIT_ACTION_TYPE ON AUDIT_LOGS(ACTION_TYPE);
CREATE INDEX IDX_AUDIT_CREATED_DATE ON AUDIT_LOGS(CREATED_DATE);
CREATE INDEX IDX_AUDIT_STATUS ON AUDIT_LOGS(STATUS);

-- 로그인 이력 인덱스
CREATE INDEX IDX_LOGIN_USER_ID ON LOGIN_HISTORY(USER_ID);
CREATE INDEX IDX_LOGIN_USERNAME ON LOGIN_HISTORY(USERNAME);
CREATE INDEX IDX_LOGIN_TIME ON LOGIN_HISTORY(LOGIN_TIME);
CREATE INDEX IDX_LOGIN_IP_ADDRESS ON LOGIN_HISTORY(IP_ADDRESS);
CREATE INDEX IDX_LOGIN_STATUS ON LOGIN_HISTORY(LOGIN_STATUS);

-- 취약점 인덱스
CREATE INDEX IDX_VULN_CVE_ID ON VULNERABILITIES(CVE_ID);
CREATE INDEX IDX_VULN_SEVERITY ON VULNERABILITIES(SEVERITY_LEVEL);
CREATE INDEX IDX_VULN_STATUS ON VULNERABILITIES(STATUS);
CREATE INDEX IDX_VULN_DISCOVERY_DATE ON VULNERABILITIES(DISCOVERY_DATE);

-- 보안 사고 인덱스
CREATE INDEX IDX_INCIDENT_TYPE ON SECURITY_INCIDENTS(INCIDENT_TYPE);
CREATE INDEX IDX_INCIDENT_SEVERITY ON SECURITY_INCIDENTS(SEVERITY_LEVEL);
CREATE INDEX IDX_INCIDENT_STATUS ON SECURITY_INCIDENTS(STATUS);
CREATE INDEX IDX_INCIDENT_DETECTION_DATE ON SECURITY_INCIDENTS(DETECTION_DATE);

-- ============================================================================
-- 7. 코멘트 추가 (Add Comments)
-- ============================================================================

COMMENT ON TABLE USERS IS '사용자 정보를 저장하는 테이블';
COMMENT ON TABLE ROLES IS '역할 정보를 저장하는 테이블';
COMMENT ON TABLE USER_ROLES IS '사용자와 역할의 매핑 정보를 저장하는 테이블';
COMMENT ON TABLE PERMISSIONS IS '권한 정보를 저장하는 테이블';
COMMENT ON TABLE ROLE_PERMISSIONS IS '역할과 권한의 매핑 정보를 저장하는 테이블';
COMMENT ON TABLE AUDIT_LOGS IS '시스템 감사 로그를 저장하는 테이블';
COMMENT ON TABLE LOGIN_HISTORY IS '사용자 로그인 이력을 저장하는 테이블';
COMMENT ON TABLE SECURITY_POLICIES IS '보안 정책 정보를 저장하는 테이블';
COMMENT ON TABLE PASSWORD_POLICIES IS '패스워드 정책 정보를 저장하는 테이블';
COMMENT ON TABLE PASSWORD_HISTORY IS '패스워드 변경 이력을 저장하는 테이블';
COMMENT ON TABLE VULNERABILITIES IS '시스템 취약점 정보를 저장하는 테이블';
COMMENT ON TABLE SECURITY_INCIDENTS IS '보안 사고 정보를 저장하는 테이블';

-- ============================================================================
-- 완료 (Completed)
-- ============================================================================
